/* Real Windows acceptance. Uses installed Edge and native Electron with NEW,
 * isolated persistent profiles. Never opens the user's normal profile/state.
 * No setContent, injected app API or mocked localStorage. Fixtures are installed
 * only into profiles created by this script. Run: node scripts/acceptance-windows.cjs LABEL
 */
const { chromium, _electron } = require('playwright-core');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const vm = require('node:vm');
const { pathToFileURL } = require('node:url');
const { createHash } = require('node:crypto');
const root = path.resolve(__dirname, '..');
const content = require('../src/content.cjs');
const testExe = process.env.NCA_ACCEPTANCE_EXE && path.resolve(process.env.NCA_ACCEPTANCE_EXE);
if (testExe && testExe.toLowerCase().startsWith(path.join(process.env.LOCALAPPDATA, 'Programs/NCA Study Desk').toLowerCase())) throw new Error('Do not use the installed user executable for this acceptance');
const label = (process.argv[2] || 'current').replace(/[^a-z0-9_-]/gi, '-');
const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const out = path.join(root, 'output/playwright', `windows-${label}-${stamp}`);
fs.mkdirSync(out, { recursive: true });
const profiles = fs.mkdtempSync(path.join(os.tmpdir(), 'nca-windows-acceptance-'));
const edge = ['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', 'C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
if (!edge) throw new Error('Installed Edge is required');
const url = pathToFileURL(path.join(root, 'web/index.html')).href;
const sha = f => createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const report = { testedAt: new Date().toISOString(), platform: process.platform, node: process.version, contentVersion: content.version, appVersion: require('../package.json').version, originalFile: url, isolatedProfiles: profiles, methods: ['native file:// navigation', 'native localStorage', 'native Electron IPC', 'persistent isolated profiles'], files: {}, checks: [], errors: [], remoteRequests: [], limitations: ['Automated UI acceptance does not establish learner mastery.', 'Mobile widths are desktop viewport checks, not a physical phone.', 'Installed executable is inspected read-only; it is not updated or launched.'] };
for (const f of ['package.json', 'content/nca-content-v0.2.json', 'web/index.html', 'src/content.cjs', 'src/renderer/renderer.js', 'src/state.cjs', 'src/main.cjs']) report.files[f] = sha(path.join(root, f));
function save() { fs.writeFileSync(path.join(out, 'acceptance.json'), JSON.stringify(report, null, 2)); }
async function check(name, fn) { try { const detail = await fn(); report.checks.push({ name, status: 'PASS', detail }); console.log('PASS ' + name); } catch (e) { report.checks.push({ name, status: 'FAIL', error: e.stack }); console.error('FAIL ' + name + ': ' + e.message); } save(); }
function observe(page, kind) { page.setDefaultTimeout(10000); page.on('pageerror', e => report.errors.push({ kind, type:'pageerror', message: e.message })); page.on('console',m=>{if(m.type()==='error')report.errors.push({kind,type:'console-error',message:m.text()});}); page.on('request', r => { if (/^https?:/.test(r.url())) report.remoteRequests.push({ kind, url: r.url() }); }); }
const webState = page => page.evaluate(() => JSON.parse(localStorage.getItem('nca-study-desk-html-v1')));
const deskState = async page => { await page.evaluate(() => saveChain); return page.evaluate(() => window.ncaDesk.getState()); };
const navWeb = (p, view) => p.locator(`#tool-nav [data-view="${view}"]`).click();
const navDesk = (p, view) => p.locator(`[data-nav="${view}"]`).click();
async function webDay(p, day, budget) { await navWeb(p, 'today'); await p.locator(`[data-budget="${budget}"]`).click(); await p.locator(`[data-day="${day}"]`).first().click(); }
async function deskDay(p, day, budget) { await navDesk(p, 'home'); await p.locator(`[data-budget="${budget}"]`).click(); await p.locator(`[data-lesson="${day}"]`).first().click(); }
async function choose(p, ids, desk = false) { for (const id of ids) await p.locator(`input[name="${desk ? 'answer' : 'option'}"][value="${id}"]`).check(); }
async function launchWeb(profile) { const ctx = await chromium.launchPersistentContext(profile, { executablePath: edge, headless: true, viewport: { width: 1440, height: 1000 }, offline: true, acceptDownloads: true }); const p = ctx.pages()[0] || await ctx.newPage(); observe(p, 'web'); await p.goto(url); await p.locator('#view h2').waitFor(); return { ctx, p }; }
async function launchDesk(profile) { const env = { ...process.env, NCA_DESK_USER_DATA: profile }; delete env.ELECTRON_RUN_AS_NODE; const app = await _electron.launch({ executablePath: testExe || require('electron'), args: [...(testExe ? [] : [root]), '--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-backgrounding-occluded-windows'], cwd: root, env }); const p = await app.firstWindow(); observe(p, 'electron'); await p.locator('#app h1').waitFor(); return { app, p }; }
async function webTests() {
  const profile = path.join(profiles, 'edge'); let { ctx, p } = await launchWeb(profile);
  report.browser = await ctx.browser().version();
  try {
    await check('web: original-path offline homepage', async () => { assert.equal(p.url(), url); assert.equal(await p.locator('#home').count(), 1); await p.screenshot({ path: path.join(out, 'web-home.png') }); });
    for (const l of content.lessons) for (const budget of [20, 45, 60]) await check(`web: Day ${l.day} / ${budget} minutes cards + ${content.budgets[budget].questions} questions`, async () => {
      await webDay(p, l.day, budget); const cards = content.cards.filter(c => c.day === l.day); assert.equal(await p.locator('.knowledge').count(), cards.length);
      for (const c of cards) { const row = p.locator(`[data-knowledge-id="${c.webId}"]`); assert.equal(await row.locator('h3').textContent(), c.title); assert.ok((await row.textContent()).includes(c.conclusion)); }
      assert.equal(await p.locator('.knowledge details').first().evaluate(e => e.open), budget !== 20);
      await p.locator('#goQuiz').click(); assert.equal((await webState(p)).quiz.ids.length, content.budgets[budget].questions); assert.equal(await p.locator('.answer').count(), 0);
    });
    await check('web: wrong answer, answer explanation and first-attempt record', async () => { await webDay(p, 1, 20); await p.locator('#goQuiz').click(); await p.locator('#submit').click(); assert.equal((await webState(p)).attempts.length, 0); await choose(p, ['a']); await p.locator('#submit').click(); assert.ok((await p.locator('.answer').textContent()).includes('这题暂时答错了')); assert.ok((await p.locator('.answer').textContent()).includes('正确答案：')); const s = await webState(p); assert.equal(s.attempts[0].first, true); assert.equal(s.reviews['q-q1'].reason, '答错'); });
    await check('web: guessed correct + multiple choice + uncertain card', async () => { await webDay(p, 2, 20); await p.locator('[data-status="cpu-gpu|uncertain"]').click(); await p.locator('#goQuiz').click(); await choose(p, ['a']); await p.locator('#guess').check(); await p.locator('#submit').click(); assert.equal((await webState(p)).reviews['q-q2'].reason, '猜对'); await p.locator('#next').click(); assert.equal(await p.locator('input[name="option"][type="checkbox"]').count(), 4); await choose(p, ['a', 'b']); await p.locator('#submit').click(); assert.equal((await webState(p)).attempts.at(-1).correct, true); assert.equal((await webState(p)).reviews['card-cpu-gpu'].active, true); });
    await check('web: review returns to exact card; retry preserves first record', async () => { await navWeb(p, 'review'); const original = (await webState(p)).attempts[0]; await p.locator('[data-card="ai"]').first().click(); assert.equal(await p.locator('.knowledge').count(), 1); assert.equal(await p.locator('.knowledge').getAttribute('data-knowledge-id'), 'ai'); await navWeb(p, 'review'); await p.locator('[data-redo="q1"]').click(); await choose(p, ['b']); await p.locator('#submit').click(); const s = await webState(p); assert.deepEqual(s.attempts[0], original); assert.equal(s.attempts.at(-1).first, false); assert.equal(s.attempts.at(-1).correct, true); });
    await check('web: per-question uncertainty available', async () => { await webDay(p, 3, 20); await p.locator('#goQuiz').click(); assert.equal(await p.locator('#uncertain').count(), 1, 'Only a card uncertainty flag exists; no per-question uncertainty flag'); await choose(p, [content.questions.find(q => q.day === 3).answer[0]]); await p.locator('#uncertain').check(); await p.locator('#submit').click(); assert.equal((await webState(p)).attempts.at(-1).uncertain, true); });
    await check('web: confidence draft survives selecting answers and refresh',async()=>{await webDay(p,3,20);await p.locator('#goQuiz').click();await p.locator('#guess').check();await p.locator('#uncertain').check();await choose(p,['a']);assert.equal(await p.locator('#guess').isChecked(),true);assert.equal(await p.locator('#uncertain').isChecked(),true);await p.reload();assert.equal(await p.locator('#guess').isChecked(),true);assert.equal(await p.locator('#uncertain').isChecked(),true);assert.equal(await p.locator('input[name="option"][value="a"]').isChecked(),true);});
    await check('web: search knowledge and questions', async () => { await navWeb(p, 'sources'); await p.locator('#search').fill('CUDA'); assert.ok(await p.locator('[data-found-card]').count() > 0); assert.ok(await p.locator('[data-found-q]').count() > 0); await p.locator('[data-found-card]').first().click(); assert.equal(await p.locator('.knowledge').count(), 1); });
    await check('web: responsive 360/390/430px learning, quiz, review and search', async () => { for (const width of [360,390,430]) { await p.setViewportSize({ width, height: 900 }); for (const v of ['today','learn','quiz','review','sources']) { await navWeb(p, v); const size = await p.evaluate(() => ({ viewport: innerWidth, scroll: document.documentElement.scrollWidth })); assert.ok(size.scroll <= size.viewport, `${width}px ${v}: overflow ${size.scroll}`); } } await p.setViewportSize({ width: 390, height: 900 }); await webDay(p, content.lessons.at(-1).day, 20); await p.screenshot({ path: path.join(out, 'web-mobile-learning.png') }); await p.locator('#goQuiz').click(); await p.screenshot({ path: path.join(out, 'web-mobile-quiz.png') }); });
    await check('web: real backup download', async () => { await navWeb(p, 'sources'); const dl = p.waitForEvent('download'); await p.locator('#exportLocal').click(); const download = await dl; const target = path.join(out, 'web-isolated-backup.json'); await download.saveAs(target); const exported = JSON.parse(fs.readFileSync(target)); assert.deepEqual(exported.state.attempts, (await webState(p)).attempts); });
    await check('web: native localStorage refresh + browser close/reopen persistence', async () => { const before = await webState(p); await p.reload(); assert.deepEqual((await webState(p)).attempts, before.attempts); await ctx.close(); ({ctx,p} = await launchWeb(profile)); assert.deepEqual((await webState(p)).attempts, before.attempts); assert.deepEqual((await webState(p)).reviews, before.reviews); });
    await check('web: Day 3–8 complete teaching renders before input practice',async()=>{for(const l of content.lessons.filter(l=>l.teachingTrial)){await webDay(p,l.day,45);assert.equal(await p.locator('[data-teaching-day]').count(),1);assert.equal(await p.locator('[data-full-lesson]').count(),l.teachingTrial.fullLesson.sections.length);assert.equal(await p.locator('[data-teaching-exercise]').count(),l.teachingTrial.exercises.length);assert.equal(await p.locator('.material-guide').count(),1);assert.equal(await p.locator('[data-full-lesson]').first().evaluate(e=>e.open),true);assert.ok(await p.locator('[data-teaching-translation]').evaluateAll(rows=>rows.every(e=>!e.open)));assert.ok(await p.locator('[data-teaching-feedback]').evaluateAll(rows=>rows.every(e=>!e.open)));}});
    await check('web: understanding answer and revision persist without changing quiz scores',async()=>{await webDay(p,3,45);const section=p.locator('[data-teaching-exercise="P-D03-01"]');const original='隔离验收原答：应用组织业务流程，框架组织模型计算，库提供可复用能力。';const revision=original+' 驱动支持系统使用设备；各层职责不能互相替代。';const quizBefore=(await webState(p)).attempts;await section.locator('[data-understanding-answer]').fill(original);await section.locator('[data-understanding-confidence]').selectOption('uncertain');await section.locator('[data-understanding-prior]').selectOption('unseen');await section.locator('[data-understanding-submit]').click();await section.locator('[data-understanding-history] details').waitFor();let s=await webState(p);let rows=s.understanding.attempts.filter(a=>a.exerciseId==='P-D03-01');assert.equal(rows.length,1);assert.equal(rows[0].answerText,original);assert.equal(rows[0].confidence,'uncertain');assert.equal(rows[0].priorExposure,'unseen');assert.equal(rows[0].referenceSeenAt,null);assert.equal(rows[0].translationSeenAt,null);assert.deepEqual(s.attempts,quizBefore);await section.locator('[data-understanding-answer]').fill(revision);await section.locator('[data-understanding-submit]').click();await p.waitForFunction(()=>document.querySelectorAll('[data-teaching-exercise="P-D03-01"] [data-understanding-history] details').length===2);s=await webState(p);rows=s.understanding.attempts.filter(a=>a.exerciseId==='P-D03-01');assert.equal(rows.length,2);assert.equal(rows[0].answerText,original);assert.equal(rows[1].answerText,revision);assert.equal(rows[1].revisionOf,rows[0].id);await p.reload();await p.locator('[data-teaching-exercise="P-D03-01"]').waitFor();assert.equal(await p.locator('[data-teaching-exercise="P-D03-01"] [data-understanding-history] details').count(),2);assert.ok((await p.locator('[data-teaching-exercise="P-D03-01"] [data-understanding-history]').textContent()).includes(original));});
    for(const l of content.lessons.filter(l=>l.day>=5))await check(`web: Day ${l.day} actual correct submission and explanations`,async()=>{const q=content.questions.find(q=>q.id===l.questionIds[0]);await webDay(p,l.day,20);await p.locator('#goQuiz').click();await choose(p,q.answer);await p.locator('#submit').click();assert.equal((await webState(p)).attempts.at(-1).correct,true);assert.ok((await p.locator('.answer').textContent()).includes(q.explanation));assert.equal(await p.locator('.analysis > div').count(),q.options.length);});
    for(const l of content.lessons.filter(l=>l.day>=5))await check(`web: Day ${l.day} multiple-choice real selection and scoring`,async()=>{const q=content.questions.find(q=>q.day===l.day&&q.type==='multiple');assert.ok(q,'No multi-choice question in this lesson');await navWeb(p,'sources');await p.locator('#search').fill(q.stem);await p.locator(`[data-found-q="${q.webId}"]`).click();assert.equal(await p.locator('input[name="option"][type="checkbox"]').count(),q.options.length);await choose(p,q.answer);await p.locator('#submit').click();const a=(await webState(p)).attempts.at(-1);assert.equal(a.correct,true);assert.deepEqual(a.selected,q.answer);});
  } finally { await ctx.close(); }
  await check('web: v0.1 fixture retained across native load and retry', async () => { const fixture = { version:1, view:'review', cardStatus:{ai:'explain'}, activeCard:'ai', quiz:{ids:['q1','q2','q3','q4','q5'],index:0,selected:[],submitted:false,runIds:['legacy-web-attempt']}, attempts:[{id:'legacy-web-attempt',question:'q1',selected:['a'],correct:false,guessed:false,doubt:false,first:true,at:'2026-09-19T00:00:00.000Z'}], reviews:{'q-q1':{key:'q-q1',kind:'question',id:'q1',active:true,reason:'答错'}} }; const x = await launchWeb(path.join(profiles, 'edge-legacy')); try { await x.p.evaluate(s => localStorage.setItem('nca-study-desk-html-v1', JSON.stringify(s)), fixture); await x.p.reload(); await x.p.locator('[data-redo="q1"]').waitFor(); assert.deepEqual((await webState(x.p)).attempts, fixture.attempts); await x.p.locator('[data-redo="q1"]').click(); await choose(x.p,['b']); await x.p.locator('#submit').click(); assert.equal((await webState(x.p)).attempts.at(-1).first,false); assert.deepEqual((await webState(x.p)).attempts[0],fixture.attempts[0]); } finally { await x.ctx.close(); } });
}
async function desktopTests() {
  const profile = path.join(profiles, 'electron'); let {app,p} = await launchDesk(profile); report.electron = await app.evaluate(({app}) => ({version:process.versions.electron, appVersion:app.getVersion(), userData:app.getPath('userData'), executable:process.execPath}));
  if(testExe)report.electron.executableSHA256=sha(testExe);
  try {
    await check('electron: native startup and shared content parity', async () => { assert.equal(report.electron.userData, profile); assert.equal(report.electron.appVersion, report.appVersion); assert.deepEqual(await p.evaluate(() => window.ncaDesk.getContent()), content); await p.screenshot({ path:path.join(out,'electron-home.png') }); });
    await check('electron: 40 consecutive navigations retain one click listener',async()=>{const cd=await p.context().newCDPSession(p),counts=[];const start=Date.now();for(let i=0;i<40;i++){await navDesk(p,['home','learn','review','sources'][i%4]);const r=await cd.send('Runtime.evaluate',{expression:'document.querySelector("[data-nav=home]")'});const listeners=await cd.send('DOMDebugger.getEventListeners',{objectId:r.result.objectId});counts.push(listeners.listeners.filter(l=>l.type==='click').length);}assert.ok(counts.every(n=>n===1),'Repeated render accumulated click listeners');await deskState(p);return{counts,elapsedMs:Date.now()-start};});
    for (const l of content.lessons) {
      for (const budget of [20,45,60]) await check(`electron: Day ${l.day} / ${budget} minutes cards + ${content.budgets[budget].questions} questions`, async () => { await deskDay(p,l.day,budget); assert.equal(await p.locator('.knowledge-card').count(),l.cardIds.length); assert.equal(await p.locator('.knowledge-card details').first().evaluate(e=>e.open),budget!==20); await p.locator('#toPractice').click(); assert.equal((await deskState(p)).session.questionIds.length,content.budgets[budget].questions); assert.equal(await p.locator('.answer').count(),0); });
    }
    await check('electron: wrong, guessed, uncertain, single + multiple answers', async () => { await deskDay(p,1,20); await p.locator('#toPractice').click(); await p.locator('#submitAnswer').click(); assert.equal((await deskState(p)).attempts.length,0); await choose(p,['a'],true); await p.locator('#submitAnswer').click(); assert.ok((await p.locator('.answer').textContent()).includes('这题暂时答错了')); assert.equal((await deskState(p)).reviews['Q-ORIGINAL-001'].reason,'答错'); await deskDay(p,2,20); await p.locator('[data-card-status="card-cpu-gpu|uncertain"]').click(); await p.locator('#toPractice').click(); await choose(p,['a'],true); await p.locator('#guess').check(); await p.locator('#submitAnswer').click(); assert.equal((await deskState(p)).reviews['Q-ORIGINAL-002'].reason,'猜对'); await p.locator('#nextQuestion').click(); await choose(p,['a','b'],true); await p.locator('#uncertain').check(); await p.locator('#submitAnswer').click(); const s=await deskState(p); assert.equal(s.attempts.at(-1).correct,true); assert.equal(s.attempts.at(-1).uncertain,true); assert.equal(s.reviews['Q-ORIGINAL-003'].reason,'还不确定'); });
    await check('electron: review returns to exact card; retry preserves first record', async () => { await navDesk(p,'review'); const before=(await deskState(p)).attempts[0]; await p.locator('[data-card="card-ai-ml-dl"]').first().click(); assert.equal(await p.locator('.knowledge-card').count(),1); assert.equal(await p.locator('.knowledge-card').getAttribute('data-knowledge-id'),'card-ai-ml-dl'); await navDesk(p,'review'); await p.locator('[data-redo="Q-ORIGINAL-001"]').click(); await choose(p,['b'],true); await p.locator('#submitAnswer').click(); const s=await deskState(p); assert.deepEqual(s.attempts[0],before); assert.equal(s.attempts.at(-1).firstAttempt,false); assert.equal(s.attempts.at(-1).correct,true); });
    await check('electron: confidence flags survive changing selected option and refresh', async () => { await deskDay(p,3,20); await p.locator('#toPractice').click(); await p.locator('#guess').check(); await p.locator('#uncertain').check(); await choose(p,['a'],true); assert.equal(await p.locator('#guess').isChecked(),true,'Guessed flag cleared while choosing answer'); assert.equal(await p.locator('#uncertain').isChecked(),true,'Uncertain flag cleared while choosing answer');await deskState(p);await p.reload();await p.locator('#guess').waitFor();assert.equal(await p.locator('#guess').isChecked(),true);assert.equal(await p.locator('#uncertain').isChecked(),true); });
    await check('electron: search and progress screens', async () => { await navDesk(p,'sources'); await p.locator('#search').fill('CUDA'); assert.ok((await p.locator('#searchResult').textContent()).includes('CUDA')); await navDesk(p,'progress'); assert.ok((await p.locator('#app').textContent()).includes('首次作答正确率')); await p.screenshot({path:path.join(out,'electron-progress.png')}); });
    await check('electron: search result opens the matching knowledge card',async()=>{await navDesk(p,'sources');await p.locator('#search').fill('CUDA');assert.ok(await p.locator('#searchResult [data-found-card]').count()>0,'Search displays plain text only; cannot open card');await p.locator('#searchResult [data-found-card]').first().click();assert.equal(await p.locator('.knowledge-card').count(),1);});
    await check('electron: pause can resume the saved unfinished question',async()=>{await deskDay(p,2,20);await p.locator('#toPractice').click();await choose(p,['a'],true);await p.locator('#submitAnswer').click();await p.locator('#nextQuestion').click();await choose(p,['a'],true);const before=(await deskState(p)).session;await p.locator('#exitPractice').click();assert.equal(await p.locator('#resumePractice').count(),1,'No home button resumes unfinished practice');await p.locator('#resumePractice').click();const after=(await deskState(p)).session;assert.equal(after.index,before.index);assert.deepEqual(after.draft,before.draft);assert.equal(after.questionId,before.questionId);});
    await check('electron: real disk save + refresh + process close/reopen persistence', async () => { const before=await deskState(p); const disk=JSON.parse(fs.readFileSync(path.join(profile,'study-state-v1.json'))); assert.deepEqual(disk.attempts,before.attempts); await p.reload(); await p.locator('#app h1').waitFor(); assert.deepEqual((await deskState(p)).attempts,before.attempts); await app.close(); ({app,p}=await launchDesk(profile)); assert.deepEqual((await deskState(p)).attempts,before.attempts); assert.deepEqual((await deskState(p)).reviews,before.reviews); });
    await check('electron: Day 3–8 complete teaching renders before input practice',async()=>{for(const l of content.lessons.filter(l=>l.teachingTrial)){await deskDay(p,l.day,45);assert.equal(await p.locator('[data-teaching-day]').count(),1);assert.equal(await p.locator('[data-full-lesson]').count(),l.teachingTrial.fullLesson.sections.length);assert.equal(await p.locator('[data-teaching-exercise]').count(),l.teachingTrial.exercises.length);assert.equal(await p.locator('.material-guide').count(),1);assert.equal(await p.locator('[data-full-lesson]').first().evaluate(e=>e.open),true);assert.ok(await p.locator('[data-teaching-translation]').evaluateAll(rows=>rows.every(e=>!e.open)));assert.ok(await p.locator('[data-teaching-feedback]').evaluateAll(rows=>rows.every(e=>!e.open)));}});
    await check('electron: understanding answer and revision persist on disk without changing quiz scores',async()=>{await deskDay(p,3,45);const section=p.locator('[data-teaching-exercise="P-D03-01"]');const original='隔离桌面验收原答：应用、框架、库和驱动承担不同职责。';const revision=original+' 需要根据失败发生在哪一层选择核查方向。';const quizBefore=(await deskState(p)).attempts;await section.locator('[data-understanding-answer]').fill(original);await section.locator('[data-understanding-confidence]').selectOption('certain');await section.locator('[data-understanding-prior]').selectOption('unseen');await section.locator('[data-understanding-submit]').click();await section.locator('[data-understanding-history] details').waitFor();let s=await deskState(p);let rows=s.understanding.attempts.filter(a=>a.exerciseId==='P-D03-01');assert.equal(rows.length,1);assert.equal(rows[0].answerText,original);assert.equal(rows[0].confidence,'certain');assert.equal(rows[0].priorExposure,'unseen');assert.deepEqual(s.attempts,quizBefore);await section.locator('[data-understanding-answer]').fill(revision);await section.locator('[data-understanding-submit]').click();await p.waitForFunction(()=>document.querySelectorAll('[data-teaching-exercise="P-D03-01"] [data-understanding-history] details').length===2);s=await deskState(p);rows=s.understanding.attempts.filter(a=>a.exerciseId==='P-D03-01');assert.equal(rows[0].answerText,original);assert.equal(rows[1].answerText,revision);assert.equal(rows[1].revisionOf,rows[0].id);const disk=JSON.parse(fs.readFileSync(path.join(profile,'study-state-v1.json')));assert.equal(disk.understanding.attempts.filter(a=>a.exerciseId==='P-D03-01').length,2);await p.reload();await p.locator('[data-teaching-exercise="P-D03-01"]').waitFor();assert.equal(await p.locator('[data-teaching-exercise="P-D03-01"] [data-understanding-history] details').count(),2);});
    for(const l of content.lessons.filter(l=>l.day>=5))await check(`electron: Day ${l.day} actual correct submission and explanations`,async()=>{const q=content.questions.find(q=>q.id===l.questionIds[0]);await deskDay(p,l.day,20);await p.locator('#toPractice').click();await choose(p,q.answer,true);await p.locator('#submitAnswer').click();assert.equal((await deskState(p)).attempts.at(-1).correct,true);assert.ok((await p.locator('.answer').textContent()).includes(q.explanation));assert.equal(await p.locator('.option-analysis > div').count(),q.options.length);});
    for(const l of content.lessons.filter(l=>l.day>=5))await check(`electron: Day ${l.day} multiple-choice real selection and scoring`,async()=>{const q=content.questions.find(q=>q.day===l.day&&q.type==='multiple');assert.ok(q,'No multi-choice question in this lesson');await navDesk(p,'sources');await p.locator('#search').fill(q.stem);await p.locator(`[data-found-q="${q.id}"]`).click();assert.equal(await p.locator('input[name="answer"][type="checkbox"]').count(),q.options.length);await choose(p,q.answer,true);await p.locator('#submitAnswer').click();const a=(await deskState(p)).attempts.at(-1);assert.equal(a.correct,true);assert.deepEqual(a.selected,q.answer);});
  } finally { await app.close(); }
  await check('electron: v0.1 disk fixture retained across native load and retry',async()=>{ const fixture={schemaVersion:1,settings:{budget:45},learning:{cardStates:{'card-ai-ml-dl':'explain'}},attempts:[{id:'legacy-desktop-attempt',questionId:'Q-ORIGINAL-001',selected:['a'],correct:false,guessed:false,uncertain:false,questionable:false,answeredAt:'2026-09-19T00:00:00.000Z',firstAttempt:true,mode:'practice'}],reviews:{'Q-ORIGINAL-001':{questionId:'Q-ORIGINAL-001',createdAt:'2026-09-19T00:00:00.000Z',reviewCount:0,active:true,dueAt:'2026-09-20T00:00:00.000Z',reason:'答错'}},notes:[{id:'legacy-note',text:'Isolated legacy fixture; not real learner evidence.',createdAt:'2026-09-19T00:00:00.000Z',updatedAt:'2026-09-19T00:00:00.000Z'}],session:{screen:'review',cardId:'card-ai-ml-dl',questionId:null},updatedAt:null}; const dir=path.join(profiles,'electron-legacy');fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,'study-state-v1.json'),JSON.stringify(fixture)); const x=await launchDesk(dir);try{assert.deepEqual((await deskState(x.p)).attempts,fixture.attempts);await x.p.locator('[data-redo="Q-ORIGINAL-001"]').click();await choose(x.p,['b'],true);await x.p.locator('#submitAnswer').click();const s=await deskState(x.p);assert.deepEqual(s.attempts[0],fixture.attempts[0]);assert.equal(s.attempts.at(-1).firstAttempt,false);assert.deepEqual(s.notes,fixture.notes);}finally{await x.app.close();}});
}
async function inspectInstalled() { await check('installed version: read-only executable and ASAR inventory',async()=>{const asar=require('@electron/asar');const dir=path.join(process.env.LOCALAPPDATA,'Programs/NCA Study Desk');const exe=path.join(dir,'NCA Study Desk.exe');const archive=path.join(dir,'resources/app.asar');if(!fs.existsSync(exe)){report.installed={found:false};return;}const pkg=JSON.parse(asar.extractFile(archive,'package.json'));const old=vm.runInNewContext(`(function(){const module={exports:{}};${asar.extractFile(archive,'src/content.cjs').toString()};return module.exports;})()`);report.installed={found:true,path:exe,version:pkg.version,exeSHA256:sha(exe),asarSHA256:sha(archive),cards:old.cards.length,questions:old.questions.length,contentVersion:old.version||'not recorded',fileTime:fs.statSync(exe).mtime.toISOString(),updated:false,launched:false};const installer='C:/Users/asus/Documents/Codex/NCA-Study-Desk-Build/NCA-Study-Desk-Setup-0.1.0-x64.exe';report.oldInstaller=fs.existsSync(installer)?{path:installer,sha256:sha(installer),fileTime:fs.statSync(installer).mtime.toISOString()}:null;}); }
(async()=>{ if(process.platform!=='win32')throw new Error('This acceptance must run on Windows'); await inspectInstalled(); if(process.argv[3]!=='desktop')await webTests(); if(process.argv[3]!=='web')await desktopTests(); await check('runtime: no page exceptions or remote requests',async()=>{assert.deepEqual(report.errors,[]);assert.deepEqual(report.remoteRequests,[]);});await check('evidence: tested source hashes unchanged throughout this run',async()=>{for(const[f,hash]of Object.entries(report.files))assert.equal(sha(path.join(root,f)),hash,`${f} changed during acceptance`);});report.finishedAt=new Date().toISOString();report.summary={pass:report.checks.filter(c=>c.status==='PASS').length,fail:report.checks.filter(c=>c.status==='FAIL').length};save();console.log(JSON.stringify({out,summary:report.summary}));if(report.summary.fail)process.exitCode=1;})().catch(e=>{report.fatal=e.stack;save();console.error(e);process.exitCode=1;});
